
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Return the cached host list (populated at startup / on reload, tech-gui.md §4.2).
 */
async listHosts() : Promise<Result<HostDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_hosts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reload hosts from the shared config, refresh the cache, restart the pollers,
 * and broadcast the new list via `hosts-loaded` (tech-gui.md §4.2). Also the
 * startup entry point: the frontend calls it once its event bridge is up.
 */
async reloadHosts() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_hosts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add or edit a host and persist to `hosts.toml` (tech-gui.md §4.2, Stage 4.1).
 * Upserts by name. Editing an SSH-config import adopts it: the saved copy is a manual
 * entry that `merge_hosts` then prefers over the parsed one, so `~/.ssh/config` itself
 * is still never written. The frontend calls `reload_hosts` afterwards to refresh the
 * merged cache + restart the pollers. Secrets stay backend-side (§3.4): the payload's
 * password/identity never left the backend.
 */
async saveHost(input: HostInputDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_host", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a manual host by name and persist (tech-gui.md §4.2, Stage 4.1). Only manual
 * entries live in `hosts.toml`, so an SSH-config name — or a missing one — is a no-op
 * success: the desired end state (absent) already holds.
 */
async deleteHost(name: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_host", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List saved snippets from the shared `snippets.toml` (tech-gui.md §4.2).
 */
async listSnippets() : Promise<Result<SnippetDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snippets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upsert a snippet by name and persist the whole list (tech-gui.md §4.2). A new
 * name appends; an existing name is replaced in place (an in-place edit). A rename
 * is a frontend delete-old + save-new, since the contract keys snippets on `name`.
 */
async saveSnippet(snippet: SnippetDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_snippet", { snippet }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the snippet named `name` and persist (tech-gui.md §4.2). A missing name is
 * a no-op success — the desired end state (absent) already holds.
 */
async deleteSnippet(name: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snippet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute a snippet on one or more hosts (tech-gui.md §4.2). Substitutes the
 * provided values into declared placeholders, then fires one task per host that
 * runs the command over a fresh SSH session and emits a `snippet-result` (§4.3).
 * Fire-and-forget: results arrive as events, mirroring the core's own model.
 */
async executeSnippet(snippetName: string, hostNames: string[], params: Partial<{ [key in string]: string }>) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_snippet", { snippetName, hostNames, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a terminal for `host_name`, streaming raw output into `on_output`. Returns
 * the public session id used by the write/resize/close commands (tech-gui.md §4.2).
 */
async terminalOpen(hostName: string, cols: number, rows: number, onOutput: TAURI_CHANNEL<TerminalBytes>) : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_open", { hostName, cols, rows, onOutput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send keystrokes / pasted bytes to a terminal (tech-gui.md §4.2). Input is
 * low-volume, so the ordinary `number[]` path is fine here (only output is raw).
 */
async terminalWrite(sessionId: number, data: number[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_write", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reflow a terminal to `cols` x `rows` (tech-gui.md §4.2).
 */
async terminalResize(sessionId: number, cols: number, rows: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_resize", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close a terminal and its connection (tech-gui.md §4.2). The frontend has already
 * dropped the tab, so the resulting `PtyExited` emits no `terminal-exited` (§3.4).
 */
async terminalClose(sessionId: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_close", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open an SFTP session for `host_name` (tech-gui.md §4.2). Awaits the core connect,
 * registers the manager under a fresh public id, and spawns the per-session
 * forwarder; the `sftp-connected` ack then arrives stamped with that id (§3.4).
 */
async sftpOpen(hostName: string) : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_open", { hostName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List a remote directory (tech-gui.md §4.2); the result arrives as `sftp-dir-listed`.
 */
async sftpList(sessionId: number, path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_list", { sessionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a remote directory (tech-gui.md §4.2); completion arrives as `sftp-op-done`.
 */
async sftpMkdir(sessionId: number, path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_mkdir", { sessionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename / move a remote path (tech-gui.md §4.2).
 */
async sftpRename(sessionId: number, from: string, to: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_rename", { sessionId, from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a remote file (falls back to an empty directory in the core) (tech-gui.md §4.2).
 */
async sftpDelete(sessionId: number, path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_delete", { sessionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a remote file's preview bytes (tech-gui.md §4.2); arrives as `file-preview`.
 */
async sftpPreview(sessionId: number, path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_preview", { sessionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close an SFTP session and its connection (tech-gui.md §4.2).
 */
async sftpClose(sessionId: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sftp_close", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List a local directory (tech-gui.md §4.2). Returns directly off the async worker;
 * the GUI never emits `LocalDirListed` (§4.3). The core prepends a `..` entry and
 * sorts dirs-first.
 */
async listLocalDir(path: string) : Promise<Result<FileEntryDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_local_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read up to 4 KiB of a local file as UTF-8 for preview (tech-gui.md §4.2).
 */
async previewLocalFile(path: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_local_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Expand `sources` (local paths for an upload, remote paths for a download)
 * into a batch targeting `dest_dir`, listing every destination that already
 * exists. The batch waits for `transfer_commit` or `transfer_discard`.
 */
async transferPrepare(sessionId: number, direction: TransferDirectionDto, sources: string[], destDir: string) : Promise<Result<PreparedBatchDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transfer_prepare", { sessionId, direction, sources, destDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enqueue a prepared batch. Conflicts without an answer are skipped. Returns
 * the enqueued transfers so the queue panel can list them straight away.
 */
async transferCommit(sessionId: number, batchId: number, resolutions: ConflictResolutionDto[]) : Promise<Result<TransferItemDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transfer_commit", { sessionId, batchId, resolutions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop a prepared batch the user backed out of.
 */
async transferDiscard(sessionId: number, batchId: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transfer_discard", { sessionId, batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel queued or running transfers; running ones clean up after themselves.
 */
async transferCancel(sessionId: number, ids: number[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transfer_cancel", { sessionId, ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-run failed or cancelled transfers.
 */
async transferRetry(sessionId: number, ids: number[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transfer_retry", { sessionId, ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forget finished transfers the user cleared from the queue panel.
 */
async transferForget(sessionId: number, ids: number[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transfer_forget", { sessionId, ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set how many parallel connections each host's transfers may use (1–8).
 * Applies to connections opened from now on.
 */
async setTransferStreams(streams: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_transfer_streams", { streams }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Editors found installed on this machine, for the Settings picker.
 */
async detectEditors() : Promise<Result<EditorAppDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_editors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a local file in `editor`.
 */
async openLocalFile(path: string, editor: EditorDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_local_file", { path, editor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download a remote file, open it in `editor`, and upload every save back.
 * Resolves once the editor was launched; sync progress arrives as `edit-sync`.
 */
async editRemoteFile(sessionId: number, remotePath: string, editor: EditorDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_remote_file", { sessionId, remotePath, editor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Answer an `edit-sync` conflict: `overwrite` pushes the local copy over the
 * server's; otherwise the local copy is replaced with the server's version.
 */
async editResolveConflict(sessionId: number, remotePath: string, overwrite: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_resolve_conflict", { sessionId, remotePath, overwrite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Answer an `edit-sync` `modified` prompt: upload this save, or keep it local.
 */
async editConfirmUpload(sessionId: number, remotePath: string, upload: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_confirm_upload", { sessionId, remotePath, upload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run a file operation on the server of SFTP tab `session_id`.
 */
async remoteFsOp(sessionId: number, op: RemoteFsOpDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remote_fs_op", { sessionId, op }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run a file operation on this machine.
 */
async localFsOp(op: LocalFsOpDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("local_fs_op", { op }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every container on `host_name`, running ones with live CPU and memory.
 */
async dockerList(hostName: string) : Promise<Result<DockerListDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("docker_list", { hostName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start / stop / restart / pause / unpause / remove a container.
 */
async dockerAction(hostName: string, id: string, action: DockerActionDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("docker_action", { hostName, id, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The last `tail` lines of a container's log.
 */
async dockerLogs(hostName: string, id: string, tail: number) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("docker_logs", { hostName, id, tail }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What a terminal types to open a shell inside the container.
 */
async dockerShellCommand(id: string, sudo: boolean) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("docker_shell_command", { id, sudo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vpnStatus() : Promise<Result<VpnStatusDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vpn_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tunnelblick's configuration names.
 */
async vpnConfigurations() : Promise<Result<string[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vpn_configurations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hand an .ovpn/.conf/.tblk file to Tunnelblick to install.
 */
async vpnImport(path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vpn_import", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tunnelblick's state for a configuration (`CONNECTED`, `EXITING`, …).
 */
async vpnState(name: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vpn_state", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vpnConnect(name: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vpn_connect", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vpnDisconnect(name: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vpn_disconnect", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download, verify and install Tunnelblick; progress arrives as
 * `vpn-install-progress`. Resolves when it is installed (and launched).
 */
async vpnInstall() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vpn_install") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install a key on `host_name` (tech-gui.md §4.2): a new one or `key`, with
 * logins afterwards per `mode`. Fire-and-forget; reports via `key-setup-*` events.
 * One run at a time, so two runs never race a `hosts.toml` write.
 */
async startKeySetup(hostName: string, key: KeyChoiceDto, mode: AuthModeDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_key_setup", { hostName, key, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a local Ed25519 key pair in `~/.ssh`. A passphrase, when provided, is
 * used to encrypt the private key and retained only in the process unlock cache.
 */
async createSshKey(name: string, comment: string, passphrase: string) : Promise<Result<SshKeyDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_ssh_key", { name, comment, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The private keys in `~/.ssh`, for the key pickers.
 */
async listSshKeys() : Promise<Result<SshKeyDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_ssh_keys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Describe a key file the user picked by hand. Errors when it is not a private key.
 */
async inspectSshKey(path: string) : Promise<Result<SshKeyDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_ssh_key", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether an encrypted key still needs its passphrase in this app process. The
 * passphrase itself is never persisted; an unlocked key becomes locked again when
 * OmnySSH exits.
 */
async keyPassphraseRequired(path: string) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("key_passphrase_required", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate an encrypted key's passphrase and retain it in zeroizing process memory.
 * It is never written to `hosts.toml`, app settings, logs, or the frontend again.
 */
async unlockSshKey(path: string, passphrase: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_ssh_key", { path, passphrase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The app-wide default key (used by hosts that name none), if set.
 */
async getDefaultKey() : Promise<Result<string | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set (or clear, with `None`) the app-wide default key. Takes effect for new
 * connections straight away.
 */
async setDefaultKey(path: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_key", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Which key a host uses and whether it has a stored password — for the host form
 * and the key dialog. Never the password or key material.
 */
async hostAuth(hostName: string) : Promise<Result<HostAuthDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("host_auth", { hostName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a shareable public key to the remote account's `authorized_keys`. The
 * connection uses the host's existing authentication; no local identity setting
 * or password-authentication policy is changed.
 */
async installPublicKey(hostName: string, publicKey: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_public_key", { hostName, publicKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Trigger an immediate metric poll of every host (tech-gui.md §4.2). Used by the
 * settings-driven refresh cadence (§4.3); a no-op before the pollers start.
 */
async refreshMetrics() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_metrics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Query GitHub for a newer release (tech-gui.md §4.2). `None` means up to date — the
 * core swallows network/parse errors so a failed check never disrupts.
 */
async checkUpdate() : Promise<Result<UpdateInfoDto | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download and install the latest desktop bundle via `tauri-plugin-updater` (tech-gui.md
 * §4.3/§3.7). Until Stage 5 configures the updater endpoints + signing key the plugin
 * has nothing to point at, so this reports "not available yet" rather than touching the
 * running binary.
 */
async installUpdate() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the update-checker preferences from the shared config (tech-gui.md §4.3).
 */
async loadUpdateConfig() : Promise<Result<UpdateConfigDto, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_update_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the update-checker preferences to the shared config's `[update]` section
 * (tech-gui.md §4.3). Writes off the async worker — parse + atomic write are blocking.
 */
async saveUpdateConfig(config: UpdateConfigDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_update_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
editSync: EditSync,
error: Error,
filePreview: FilePreview,
hostStatusChanged: HostStatusChanged,
hostsLoaded: HostsLoaded,
keySetupComplete: KeySetupComplete,
keySetupFailed: KeySetupFailed,
keySetupProgress: KeySetupProgress,
keySetupRollback: KeySetupRollback,
metricsUpdated: MetricsUpdated,
servicesDetected: ServicesDetected,
servicesFailed: ServicesFailed,
sftpConnected: SftpConnected,
sftpDirListed: SftpDirListed,
sftpDisconnected: SftpDisconnected,
sftpOpDone: SftpOpDone,
snippetResult: SnippetResult,
terminalExited: TerminalExited,
transfersUpdated: TransfersUpdated,
updateAvailable: UpdateAvailable,
vpnInstallProgress: VpnInstallProgress
}>({
editSync: "edit-sync",
error: "error",
filePreview: "file-preview",
hostStatusChanged: "host-status-changed",
hostsLoaded: "hosts-loaded",
keySetupComplete: "key-setup-complete",
keySetupFailed: "key-setup-failed",
keySetupProgress: "key-setup-progress",
keySetupRollback: "key-setup-rollback",
metricsUpdated: "metrics-updated",
servicesDetected: "services-detected",
servicesFailed: "services-failed",
sftpConnected: "sftp-connected",
sftpDirListed: "sftp-dir-listed",
sftpDisconnected: "sftp-disconnected",
sftpOpDone: "sftp-op-done",
snippetResult: "snippet-result",
terminalExited: "terminal-exited",
transfersUpdated: "transfers-updated",
updateAvailable: "update-available",
vpnInstallProgress: "vpn-install-progress"
})

/** user-defined constants **/



/** user-defined types **/

export type ArchiveFormatDto = "tarGz" | "zip"
/**
 * How the server accepts logins after key setup.
 */
export type AuthModeDto = "keyAndPassword" | "keyOnly"
export type CommandError = { message: string }
/**
 * How the user resolved one conflict.
 */
export type ConflictActionDto = "replace" | "skip" | "keepBoth"
export type ConflictResolutionDto = { index: number; action: ConflictActionDto }
/**
 * Live connection state for a host (tech-gui.md §4.1). Internally tagged so the
 * frontend consumes a discriminated union keyed on `kind`.
 */
export type ConnectionStatusDto = { kind: "unknown" } | { kind: "connecting" } | { kind: "connected" } | { kind: "failed"; message: string }
export type ContainerDto = { id: string; name: string; image: string; state: string; status: string; ports: string; created: string; cpu?: string | null; memory?: string | null }
export type DockerActionDto = "start" | "stop" | "restart" | "pause" | "unpause" | "remove"
export type DockerListDto = { containers: ContainerDto[]; 
/**
 * The login user needed `sudo` for docker (exec shells need it too).
 */
sudo: boolean }
/**
 * A remote file open in an external editor was saved locally and is being (or
 * was) pushed back, or needs the user because the server copy changed too.
 */
export type EditSync = { sessionId: number; remotePath: string; state: EditSyncStateDto; error?: string | null }
export type EditSyncStateDto = 
/**
 * Saved locally; asking whether to upload the new version.
 */
"modified" | 
/**
 * Saved locally; uploading the new version.
 */
"uploading" | 
/**
 * The server has the saved version.
 */
"synced" | 
/**
 * The file changed on the server since it was opened — asks before overwriting.
 */
"conflict" | "failed"
/**
 * An editor found installed on this machine.
 */
export type EditorAppDto = { name: string; path: string }
/**
 * Which program opens files (Settings → Files). Internally tagged like
 * `ConnectionStatusDto`.
 */
export type EditorDto = 
/**
 * The OS default app for the file type.
 */
{ kind: "system" } | 
/**
 * A specific application (a `.app` bundle on macOS, an executable elsewhere).
 */
{ kind: "app"; name: string; path: string } | 
/**
 * A command line; `{file}` is replaced by the path (appended when absent).
 */
{ kind: "command"; command: string }
/**
 * A background error surfaced to the user.
 */
export type Error = { message: string }
/**
 * A file or directory in an SFTP panel listing (tech-gui.md §4.1). Maps from the
 * core `FileEntry`; `path` is the absolute path the frontend marks entries by.
 */
export type FileEntryDto = { name: string; path: string; size: number; isDir: boolean; 
/**
 * Last modification, seconds since the Unix epoch.
 */
modified?: number | null; 
/**
 * Permission bits (`0o7777` mask).
 */
permissions?: number | null; isLink: boolean }
/**
 * Preview bytes for a remote file (tech-gui.md §4.3). Stamped with `sessionId`; the
 * core `FilePreviewReady` carries only the path + content (§3.4).
 */
export type FilePreview = { sessionId: number; path: string; content: string }
/**
 * A host's stored credentials as far as the key dialog and the host form need
 * them: which key file it uses (a path, never key material) and whether a
 * password is stored (never the password itself). Fetched per host on demand,
 * never broadcast with the host list.
 */
export type HostAuthDto = { identityFile?: string | null; hasPassword: boolean }
/**
 * A host as the frontend sees it — password and private-key material omitted
 * (tech-gui.md §3.4). `hasKey` reports whether an identity file is configured;
 * the key path itself never crosses the boundary.
 */
export type HostDto = { name: string; hostname: string; user: string; port: number; tags: string[]; notes?: string | null; source: HostSourceDto; hasKey: boolean; passwordAuthDisabled?: boolean | null; monitoring: MonitorModeDto; monitorPort?: number | null; 
/**
 * Tunnelblick configuration brought up before connecting.
 */
vpn?: string | null }
/**
 * Inbound host form payload for `save_host` (tech-gui.md §4.1, Stage 4.1). Always
 * builds a **manual** `Host`: editing an SSH-config import saves a copy that shadows
 * it, and `~/.ssh/config` itself is never written.
 * `password`/`identityFile` arrive here (the create/edit form owns them) but never
 * travel back out: the outbound `HostDto` omits both (§3.4). Inbound only, so it
 * derives `Deserialize` (not `Serialize`).
 */
export type HostInputDto = { name: string; hostname: string; user: string; port: number; identityFile?: string | null; password?: string | null; proxyJump?: string | null; 
/**
 * Drop the stored identity file (the form's "default key / agent" choice).
 * Without it, an absent `identityFile` keeps the stored one.
 */
clearIdentity?: boolean | null; tags: string[]; notes?: string | null; monitoring?: MonitorModeDto | null; monitorPort?: number | null; 
/**
 * Tunnelblick configuration to bring up first; absent means none.
 */
vpn?: string | null }
/**
 * Host origin, mirrors `omnyssh_core::ssh::client::HostSource`.
 */
export type HostSourceDto = "sshConfig" | "manual"
/**
 * A host's connection status changed (tech-gui.md §4.3).
 */
export type HostStatusChanged = { hostName: string; status: ConnectionStatusDto }
/**
 * Full host list broadcast. Emitted by `reload_hosts` after refreshing the
 * cache; the bridge does not map `HostsLoaded` (tech-gui.md §3.4).
 */
export type HostsLoaded = HostDto[]
/**
 * Which key key-setup installs.
 */
export type KeyChoiceDto = 
/**
 * A new Ed25519 key in `~/.ssh`, named `name` (default
 * `omnyssh_<host>_ed25519`; an existing pair of that name is reused).
 */
{ kind: "generate"; name?: string | null } | 
/**
 * An existing private key.
 */
{ kind: "existing"; path: string }
/**
 * Key setup finished successfully — key auth is configured (tech-gui.md §4.3).
 * `keyPath` is the generated private-key path (a path, never key material, §3.4).
 */
export type KeySetupComplete = { hostName: string; keyPath: string; 
/**
 * Whether the server now refuses password logins, when known.
 */
passwordAuthDisabled?: boolean | null; 
/**
 * Key-only was asked for but the key could only be installed (no sudo to
 * turn passwords off).
 */
partial: boolean }
/**
 * Key setup failed before touching the server's auth config (tech-gui.md §4.3).
 * Password authentication is never disabled unless a key was verified first.
 */
export type KeySetupFailed = { hostName: string; error: string }
/**
 * A progress step of an auto key-setup run (tech-gui.md §4.3). Mapped by the shared
 * engine bridge from `CoreEvent::KeySetupProgress`; the host name identifies the run.
 */
export type KeySetupProgress = { hostName: string; step: KeySetupStepDto }
/**
 * Key setup rolled the server's sshd config back after a late failure (tech-gui.md
 * §4.3). `result` is the human-readable rollback outcome.
 */
export type KeySetupRollback = { hostName: string; result: string }
/**
 * One step of the auto key-setup flow, for the progress view (tech-gui.md §4.2/§4.3).
 * `index` is 1-based (`1..=total`); `description` is the core's human-readable label.
 * Maps from the core `KeySetupStep`. `id` names the step for the frontend's
 * translations; `description` is the core's English text.
 */
export type KeySetupStepDto = { id: string; index: number; total: number; description: string }
/**
 * A file operation on this machine.
 */
export type LocalFsOpDto = { kind: "mkdir"; path: string } | { kind: "rename"; from: string; to: string } | 
/**
 * Move to the Trash (recoverable).
 */
{ kind: "trash"; paths: string[] } | { kind: "newFile"; path: string }
/**
 * A metrics snapshot for a host (tech-gui.md §4.1). The core's `Instant` is
 * flattened to `ageSeconds` (seconds since the sample) so it can serialise.
 */
export type MetricsDto = { cpuPercent?: number | null; ramPercent?: number | null; diskPercent?: number | null; uptime?: string | null; loadAvg?: string | null; osInfo?: string | null; topProcesses: ProcessDto[]; ageSeconds: number }
/**
 * A fresh metrics sample for a host (tech-gui.md §4.3).
 */
export type MetricsUpdated = { hostName: string; metrics: MetricsDto }
/**
 * How a host is watched, mirrors `omnyssh_core::ssh::client::MonitorMode`
 * (tech-gui.md §4.1). `tcpPort` means reachability only — no login, no metrics.
 */
export type MonitorModeDto = "ssh" | "tcpPort"
/**
 * An expanded transfer batch (folders walked) awaiting `transfer_commit`.
 */
export type PreparedBatchDto = { batchId: number; files: number; bytes: number; conflicts: TransferConflictDto[] }
/**
 * A single process in the "top processes" panel (tech-gui.md §4.1).
 */
export type ProcessDto = { name: string; cpuPercent: number; memPercent: number }
/**
 * A file operation on the server that SFTP has no verb for.
 */
export type RemoteFsOpDto = 
/**
 * Delete files and folders (recursively).
 */
{ kind: "delete"; paths: string[] } | 
/**
 * Pack entries of `dir` into `dir/archive`.
 */
{ kind: "compress"; dir: string; names: string[]; archive: string; format: ArchiveFormatDto } | { kind: "extract"; archive: string; dest: string } | { kind: "chmod"; paths: string[]; mode: number; recursive: boolean } | { kind: "newFile"; path: string } | { kind: "copy"; paths: string[]; dest: string } | { kind: "move"; paths: string[]; dest: string }
/**
 * A service detected on a host with its quick-scan metrics (tech-gui.md §4.1).
 */
export type ServiceDto = { kind: ServiceKindDto; metrics: ServiceMetricDto[] }
/**
 * A service kind detected on a host, mirrors `omnyssh_core::event::ServiceKind`.
 * Wire names are lowercase (`docker`, `nginx`, `postgresql`, `redis`, `nodejs`);
 * if the core adds a kind, extend this enum so it is never silently dropped
 * (tech-gui.md §4.1).
 */
export type ServiceKindDto = "docker" | "nginx" | "postgresql" | "redis" | "nodejs"
/**
 * One quick-scan metric for a detected service (tech-gui.md §4.1). `MetricValue`
 * is integer-only today; widen this if the core adds a non-integral variant.
 */
export type ServiceMetricDto = { name: string; value: number }
/**
 * Services detected on a host by the discovery quick-scan (tech-gui.md §4.3).
 */
export type ServicesDetected = { hostName: string; services: ServiceDto[] }
/**
 * Discovery failed for a host (tech-gui.md §4.3).
 */
export type ServicesFailed = { hostName: string; message: string }
/**
 * An SFTP session connected (tech-gui.md §4.3). The per-session forwarder stamps
 * `sessionId` from the channel's owner — the core `SftpConnected` carries only the
 * host name (§3.4).
 */
export type SftpConnected = { sessionId: number; hostName: string }
/**
 * A remote directory listing completed for one SFTP tab (tech-gui.md §4.3). Stamped
 * with `sessionId`; the core `FileDirListed` carries only the path (§3.4).
 */
export type SftpDirListed = { sessionId: number; path: string; entries: FileEntryDto[] }
/**
 * An SFTP operation reported a failure (tech-gui.md §4.3). The core emits this on a
 * listing error with a human reason; it does not by itself tear the session down.
 */
export type SftpDisconnected = { sessionId: number; reason: string }
/**
 * A mutating SFTP op (upload/download/mkdir/rename/delete) finished (tech-gui.md
 * §4.3). The core's `Result<(), String>` is flattened to `ok` + an optional `error`.
 */
export type SftpOpDone = { sessionId: number; ok: boolean; error?: string | null }
/**
 * A saved command snippet as the frontend sees it (tech-gui.md §4.1). Crosses the
 * boundary both ways — outbound for `list_snippets`, inbound for `save_snippet` —
 * so it derives `Deserialize` too. Optional fields are omitted when absent, matching
 * the sparse `snippets.toml` the TUI writes.
 */
export type SnippetDto = { name: string; command: string; scope: SnippetScopeDto; host?: string | null; tags?: string[] | null; params?: string[] | null }
/**
 * Result of running a snippet on one host (tech-gui.md §4.3). Emitted directly by
 * `execute_snippet` per host (one-shot `SshSession::run_command`), not via the
 * shared bridge — the same "the command owns the result" pattern the SFTP
 * per-session forwarder uses (§3.4). The core's `Result<String, String>` is
 * flattened to `ok` + `output` (stdout on success, the error message on failure).
 */
export type SnippetResult = { hostName: string; snippetName: string; ok: boolean; output: string }
/**
 * Snippet scope, mirrors `omnyssh_core::config::snippets::SnippetScope`. Wire
 * names are lowercase (`global`, `host`).
 */
export type SnippetScopeDto = "global" | "host"
/**
 * A private key found in `~/.ssh` (or picked by hand), for the key pickers.
 * `encrypted` marks a passphrase-protected private half; `publicKey` is the
 * shareable public half and is absent only when it cannot be read without one.
 */
export type SshKeyDto = { path: string; name: string; kind?: string | null; comment?: string | null; encrypted: boolean; publicKey?: string | null }
/**
 * Raw PTY output bytes for a terminal session's per-session `Channel` (tech-gui.md
 * §3.3/§3.6). Deliberately **not** `Serialize`: that dodges the blanket
 * `Serialize -> IpcResponse` mapping (which would JSON-encode to a slow `number[]`),
 * so the bytes ride the channel as a raw `ArrayBuffer` that xterm writes directly.
 * Only ever sent, never received — the sole non-DTO on the boundary.
 */
export type TerminalBytes = number[]
/**
 * A terminal session's remote shell exited or its connection dropped (tech-gui.md
 * §4.3). Carries the **public** registry id (the bridge maps the core's inner PTY
 * id, §3.4); the frontend tears the tab down. User-initiated closes never emit this.
 */
export type TerminalExited = { sessionId: number }
/**
 * A destination that already exists, awaiting the user's choice. `index` keys
 * the answer back to the planned file; `altName` is the "keep both" name.
 */
export type TransferConflictDto = { index: number; 
/**
 * Path relative to the destination folder ("site/css/app.css").
 */
name: string; destination: string; sourceSize: number; existingSize: number; existingIsDir: boolean; altName: string }
/**
 * Which way a transfer moves bytes.
 */
export type TransferDirectionDto = "upload" | "download"
/**
 * One enqueued transfer, returned by `transfer_commit` so the queue panel can
 * list it before its first progress update lands.
 */
export type TransferItemDto = { id: number; direction: TransferDirectionDto; name: string; local: string; remote: string; size: number }
export type TransferStateDto = "queued" | "running" | 
/**
 * The connection dropped; resuming once it is back.
 */
"reconnecting" | "done" | "failed" | "cancelled"
/**
 * Batched progress/state for one transfer (the engine reports ~7×/s).
 */
export type TransferUpdateDto = { id: number; state: TransferStateDto; done: number; total: number; error?: string | null }
/**
 * Batched progress for one SFTP tab's transfer queue. The engine reports a few
 * times a second, carrying only the transfers that changed since the last batch.
 */
export type TransfersUpdated = { sessionId: number; updates: TransferUpdateDto[] }
/**
 * A newer release was found by the startup check (tech-gui.md §4.3). Mapped by the
 * shared engine bridge from `CoreEvent::UpdateAvailable`; drives the update banner.
 */
export type UpdateAvailable = { info: UpdateInfoDto }
/**
 * Update-checker preferences, mirrors core `UpdateConfig` (tech-gui.md §4.3). Crosses
 * both ways: outbound for the settings screen, inbound for `save_update_config`.
 */
export type UpdateConfigDto = { checkOnStartup: boolean; skipVersion: string }
/**
 * A newer release the app can offer (tech-gui.md §4.1). `version` is the latest
 * version (no leading `v`); `url` is the release page; `canSelfUpdate` mirrors the
 * core's self-update eligibility. The core `UpdateInfo` has no release-notes field, so
 * none is invented (§4.1).
 */
export type UpdateInfoDto = { version: string; url: string; tag: string; canSelfUpdate: boolean }
/**
 * Progress of installing Tunnelblick (`vpn_install`).
 */
export type VpnInstallProgress = { stage: VpnInstallStageDto; done: number; total: number; error?: string | null }
export type VpnInstallStageDto = "downloading" | "verifying" | "installing" | "done" | "failed"
export type VpnStatusDto = { 
/**
 * Tunnelblick can be used on this OS (macOS).
 */
supported: boolean; installed: boolean; 
/**
 * The Tunnelblick release the app installs.
 */
installsVersion: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
